networks:
  my_network:
    external: true

volumes:
  postgres:
    external: true
  redis:
    external: true

services:
  db:

  cache:

  backend:
    container_name: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
