[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.13.3"
dependencies = [
    "Django~=5.2.7",
    "django-ninja~=1.4.5",
    "django-cors-headers~=4.9.0",
    "gunicorn~=23.0.0",
    "psycopg[c]~=3.2.10",
    "whitenoise~=6.11.0",
    "watchdog~=6.0.0",
    "celery[redis]~=5.5.3",
    "playwright~=1.55.0",
    "Pillow~=12.0.0",
    "ImageHash~=4.3.2",
    "django-storages[s3]~=1.14.6",
]

[project.optional-dependencies]
dev = [
    "django-stubs~=5.2.7",
    "ruff~=0.14.0",
    "mypy~=1.18.2",
    "pytest~=8.4.2",
    "pytest-django~=4.11.1",
    "celery-types~=0.23.0",
]

[tool.ruff]
target-version = "py313"
line-length = 100
exclude = ["*/migrations/*", ".venv"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py"]
filterwarnings = [
    "ignore::pydantic.warnings.PydanticDeprecatedSince20",
]

[tool.mypy]
python_version = "3.13"
plugins = ["mypy_django_plugin.main", "pydantic.mypy"]
explicit_package_bases = true
files = ["."]

[tool.django-stubs]
django_settings_module = "config.settings"

[tool.pyright]
pythonVersion = "3.13"
