# Generated by Django 5.2.7 on 2025-12-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL of the webpage being tracked', max_length=2048, unique=True)),
                ('day', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 day', related_name='tracked_webpage_day', to=settings.AUTH_USER_MODEL)),
                ('hour', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 hour', related_name='tracked_webpage_hour', to=settings.AUTH_USER_MODEL)),
                ('minute', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 minute', related_name='tracked_webpage_min', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebpageScreenshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perceptual_hash', models.CharField(help_text='The perceptual hash of the screenshot for comparison', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the screenshot was created')),
                ('tracked_webpage', models.ForeignKey(help_text='The tracked webpage this screenshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='base.webpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
