# Generated by Django 5.2.7 on 2025-12-25 14:22

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 6-18 characters. Letters, digits and @/./+/-/_ only.', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(18)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='The URL of the webpage being tracked', max_length=2048, unique=True)),
                ('day', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 day', related_name='tracked_webpage_day', to=settings.AUTH_USER_MODEL)),
                ('hour', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 hour', related_name='tracked_webpage_hour', to=settings.AUTH_USER_MODEL)),
                ('minute', models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 minute', related_name='tracked_webpage_min', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebpageScreenshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perceptual_hash', models.CharField(help_text='The perceptual hash of the screenshot for comparison', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the screenshot was created')),
                ('tracked_webpage', models.ForeignKey(help_text='The tracked webpage this screenshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='base.webpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
