# Generated by Django 5.2.7 on 2025-12-30 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpagescreenshot',
            name='tracked_webpage',
        ),
        migrations.AddField(
            model_name='webpagescreenshot',
            name='webpage',
            field=models.ForeignKey(default=1, help_text='The webpage this screenshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='base.webpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webpage',
            name='day',
            field=models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 day', related_name='webpage_day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='hour',
            field=models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 hour', related_name='webpage_hour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='minute',
            field=models.ManyToManyField(blank=True, help_text='Users tracking this webpage every 1 minute', related_name='webpage_min', to=settings.AUTH_USER_MODEL),
        ),
    ]
