# Generated by Django 5.2.7 on 2026-01-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_webpagescreenshot_tracked_webpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='day',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='minute',
        ),
        migrations.CreateModel(
            name='WebpageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('minute', 'minute'), ('hour', 'hour'), ('day', 'day')], max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpage_trackings', to=settings.AUTH_USER_MODEL)),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='base.webpage')),
            ],
        ),
        migrations.AddField(
            model_name='webpage',
            name='users',
            field=models.ManyToManyField(help_text='Users tracking this webpage', related_name='tracked_webpages', through='base.WebpageTracking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='webpagetracking',
            constraint=models.UniqueConstraint(fields=('webpage', 'user'), name='unique_webpage_per_user'),
        ),
        migrations.AddConstraint(
            model_name='webpagetracking',
            constraint=models.CheckConstraint(condition=models.Q(('interval__in', ['minute', 'hour', 'day'])), name='valid_interval'),
        ),
    ]
