/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a new user account
         */
        post: operations["base_api_auth_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log a user in
         */
        post: operations["base_api_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Log the current user out
         */
        post: operations["base_api_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Csrf
         * @description Get CSRF token
         */
        get: operations["base_api_auth_get_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webpage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get webpages being monitored by the user
         * @description Get all webpages that the user is monitoring for the specified interval or all intervals
         */
        get: operations["base_api_webpage_webpage_get"];
        put?: never;
        /** Add a webpage to be monitored or update its interval */
        post: operations["base_api_webpage_webpage_post"];
        /**
         * Remove a webpage from being monitored by the user
         * @description Remove a webpage from user's monitoring list
         */
        delete: operations["base_api_webpage_webpage_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get optimized image
         * @description Serves optimized images with format conversion, resizing, and quality adjustment
         */
        get: operations["base_api_image_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Signup */
        Signup: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Error */
        Error: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            } | unknown[];
        };
        /** Login */
        Login: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Logout */
        Logout: {
            /**
             * Message
             * @constant
             */
            message: "Logout successful";
        };
        /** Csrf */
        Csrf: {
            /** Csrftoken */
            csrfToken: string;
        };
        /** UnauthorizedResponse */
        UnauthorizedResponse: {
            /** Detail */
            detail: string;
        };
        /** ValidationErrorResponse */
        ValidationErrorResponse: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            }[];
        };
        /** MonitorResponse */
        MonitorResponse: {
            /** Message */
            message: string;
            /**
             * Interval
             * @enum {string}
             */
            interval: "minute" | "hour" | "day";
            /** Url */
            url: string;
            /** Id */
            id: number;
        };
        /** MonitorRequest */
        MonitorRequest: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Interval
             * @enum {string}
             */
            interval: "minute" | "hour" | "day";
        };
        /** WebpageGetQuery */
        WebpageGetQuery: {
            /** Interval */
            interval?: ("minute" | "hour" | "day") | null;
        };
        /** WebpageDetail */
        WebpageDetail: {
            /**
             * Interval
             * @enum {string}
             */
            interval: "minute" | "hour" | "day";
            /** Url */
            url: string;
            /** Id */
            id: number;
            /** Screenshots */
            screenshots: string[];
        };
        /** DeleteResponse */
        DeleteResponse: {
            /**
             * Message
             * @constant
             */
            message: "Webpage monitoring removed successfully";
            /** Id */
            id: number;
            /** Url */
            url: string;
        };
        /** DeleteRequest */
        DeleteRequest: {
            /** Id */
            id: number;
        };
        /** ImageQuery */
        ImageQuery: {
            /** W */
            w?: number | null;
            /** H */
            h?: number | null;
            /**
             * Q
             * @default 75
             */
            q: number | null;
            /**
             * F
             * @default webp
             */
            f: ("webp" | "avif" | "jpeg" | "png") | null;
        };
        /** NotFoundResponse */
        NotFoundResponse: {
            /** Detail */
            detail: string;
        };
        /** BadRequestResponse */
        BadRequestResponse: {
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    base_api_auth_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Signup"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signup"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    base_api_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    base_api_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Logout"];
                };
            };
        };
    };
    base_api_auth_get_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
        };
    };
    base_api_webpage_webpage_get: {
        parameters: {
            query?: {
                interval?: ("minute" | "hour" | "day") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebpageDetail"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
        };
    };
    base_api_webpage_webpage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    base_api_webpage_webpage_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    base_api_image_image_get: {
        parameters: {
            query?: {
                w?: number | null;
                h?: number | null;
                q?: number | null;
                f?: ("webp" | "avif" | "jpeg" | "png") | null;
            };
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundResponse"];
                };
            };
        };
    };
}
